version: "2"

services:
    mysql:
        image: mysql
        ports:
            - "33060:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_USER: admin
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: proyecto
            MYSQL_ROOT_PASSWORD: secret
    web:
        build: .
        ports:
            - 8000:80
        volumes:
            - ./:/opt/data
        depends_on:
            - mysql